spring:
  datasource:
    url: jdbc:mysql://fsemysql/keepnote?verifyServerCertificate=false&allowPublicKeyRetrieval=true&useSSL=false
    username: app-user
    password: app123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8089
jwt:
  key: keepnote