spring:
  data:
    mongodb:
      authentication-database: userDb
      username: app-root
      password: root123
      database: userDb
      port: 27017
      host: fsemongo
#      uri: mongodb://fse-mongo/userDb
  application:
    name: reminder-service

server:
  port: 8081

jwt:
  key: keepnote



#
#spring:
#  data:
#    mongodb:
# #     authentication-database:
#      username: chandan
#      password: root
#      database: reminderDb
#      port: 27017
#      host: localhost
#  application:
#    name: reminder-service
#
#server:
#  port: 8081
