spring:
  data:
    mongodb:
      authentication-database: userDb
      username: app-root
      password: root123
      database: userDb
      port: 27017
      host: fsemongo
#      uri: mongodb://fse-mongo/userDb
  application:
    name: user-service
server:
  port: 8080
jwt:
  key: keepnote