spring:
  data:
    mongodb:
      authentication-database: userDb
      username: app-root
      password: root123
      database: userDb
      port: 27017
      host: fse-mongo
 #     uri: mongodb://fse-mongo/userDb
  application:
    name: note-service
server:
  port: 8082
jwt:
  key: keepnote
